### ISSUE TITLE
RSS v10 final checks

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealSolarSystem#15]
Kopernicus 0.0.7 should be going out shortly. That means we should do some final checks and, if all is well, we can release RSS v10.

What outstanding bits need work? Earth so far has been stable for me. I know I have to fix Phobos and Deimos. Is there anything else?

**Comment by grayduster** [comment]
Neptune texture is doubled up (two great storms showing instead of one - vertical direction).  Charon texture needed, assuming we don't reuse Pluto's until New Horizons is closer.  Some way of modelling Venus' atmospheric opacity would be good, perhaps the same with titan's blue atmosphere and dusty ground.  Only Neptune is really critical.

**Comment by NathanKell** [comment]
Ok. I think that's all sorted! The Phobos and Deimos stuff was because the values were just copied from the Moon but never changed. However, make sure you delete your Kopernicus/Cache/*.bin so they get rebuilt. Neptune's map has been updated and Titan's atmosphere blueified. For making the atmospheres thick, that's really EVE's (RVE's) department, the only real way to hide the surface is to implement clouds and that's what EVE is for. :)

**Comment by NathanKell** [comment]
Nope, it was that things weren't getting disabled properly. _Now_ everything is properly fixed (AFAIK; the [Neptune image from 1989 _does_ have multiple spots](http://www.mmedia.is/~bjj/data/neptune/index.html) ).

**Comment by grayduster** [comment]
@NathanKell I see you've updated the Neptune map - you may need a last update.   I think it was one of the early ones I did, incorrectly vertically flipping them - you may need to flip it vertically again.  I'm comparing the 1989 map versus the dds, and the dds storm (the one in the lighter blue area) is north of the equator, instead of south, where it should be.

**Comment by grayduster** [comment]
@NathanKell Otherwise, I don't see any other issues - yay!

**Comment by grayduster** [comment]
:+1:
