### ISSUE TITLE
Time Warp Rates Not Working Correctly

### ISSUE THREAD

**Issue by jazzyclarinetgaming** [KSP-RO/RealSolarSystem#160]
Time Warp Rates Reset to stock. Meaning they are 1x 5x 10x 50x 100x 1000x 10000x and 1000000x rather than the rss 1x 10x 100x 1000x 10000x 100000x 1000000x and 6000000x rates.

**Comment by PhineasFreak** [comment]
The timewarp rates for RSS are controlled via the TimeWarpFixer class. Since you did not provide a .log file, we can only assume that the custom warp rates do not to work because:

* **[The file that is configuring them is either missing or cannot be accessed by KSP (OS permissions).](https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/RealSolarSystem.cfg#L6-L15)**
* **[The RSS assembly used does not match the expected KSP version, since the time warp class is version-locked.](https://github.com/KSP-RO/RealSolarSystem/blob/master/Source/TimeWarpFixer.cs#L25-L26)**

If possible then please provide a .log file for further debugging.
