### ISSUE TITLE
Update for pending RO 1.7.x release

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealSolarSystem#174]
@PhineasFreak @Starwaster
What actually needs to be done for this to get it updated so I can get a RO release out. I believe beyond a recompile it doesn't really need anything else to work in base 1.7.3, but I know the breaking ground dlc made some changes that probably break things in this.

I want to know if it can be easily fixed for the dlc compatibility or if that will hold up a release for a long time and a base ksp release can  be made without dlc support. I don't plan on having the DLC support for the initial 1.7.x RO release, especially since nobody wants to do the configs for it and I don't have the DLC and won't be buying it.

**Comment by Starwaster** [comment]
I can't think of anything that BG actually broke. It adds robotics, propellers, Surface Features and deployable science.

Deployable science is largely synonymous with the Apollo missions. It could be ignored, parts disabled to make it inaccessible to players or patched to make their descriptions match Apollo hardware. (i.e. SNAP-27, moonquake science, etc)

Propellers probably won't be very interesting to the typical RO player. Or maybe they will. I don't know. They can be fuel powered or electrical. Maybe someone will want to use them for a Mars probe. They're balanced for stock so they probably would need their range extended and LF converted to kerosene.

Some of the Surface Features might be useful. They do things like add moon rocks that can be collected. The descriptions would need to be de-Kerbalized and not all of them would be appropriate for inclusion unless you like Baobab Trees. (someone must have been a Little Prince fan). There are also cryovolcanoes and geysers that might be included.

Robotics: Some of the parts are required for propellers. They could also be used to make station arms ala Canadarm. Angel-125 has already made a mod that adds actual Canadarm parts using the BG robotics though it seems a bit buggy right now but later down the road might be useful. He also made a set of robotics parts based on NASA's ATHLETE project (used in ground base construction?). Again, potentially useful but maybe not what the average RO player is looking for.

So all in all I don't really see anything here that is game breaking and some of it is either historically significant (deployables) or significant due to current events or proposals.

**Comment by PhineasFreak** [comment]
I cannot comment on the BG DLC additions/changes as i do not own it. Other than that, the two things I'd like to fix in RSS are:

* the removal of the compatibility checker (i have already posted a sample/test DLL somewhere in the RO Discord).
* the addition of custom terrain presets (i supplied @pap1723 with a sample config but we need to add all terrain levels).

**Comment by Starwaster** [comment]
@PhineasFreak if we do add Surface Features, custom terrain presets are going to be a must to control spawn levels

**Comment by raidernick** [comment]
@PhineasFreak ok so you will work on getting this updated then? Also before the next release can you please add vostochny. I noticed this launch site was missing and it's already had several successful orbital launches.

**Comment by PhineasFreak** [comment]
I cannot promise anything as i have pretty much quit playing KSP. The stuff that i mentioned are very easy to implement right now without any testing but new launch sites require a ton of fiddling around for correct placement.

**Comment by ryancoates321** [comment]
@PhineasFreak do u did help to maintain the mod? and cool

**Comment by raidernick** [comment]
So can this just get a recompile for 1.7.3 then? I'm trying to get the RO release out.
