### ISSUE TITLE
[questions] French translation

### ISSUE THREAD

**Issue by vinix38** [KSP-RO/RealSolarSystem#228]
Hi, I am currently in the process of translating RSS in French, and I have a few questions:

- Celestial bodies' descriptions are often long single complex sentences (5+ clauses), which are really hard to translate correctly . Is it ok to break them down into smaller and simpler sentences? 
- In a few cases, famous spacecraft orbiting the body are mentioned. Can I add more of those? If yes, should I add them in the English version as well?
- Lots of biomes bear the Latin name of the feature. So far, I have translated them to the French names if they existed (Mare Tranquillitatis --> [Mer de la Tranquilité](https://fr.wikipedia.org/wiki/Mer_de_la_Tranquillité) , "Tranquility Sea"), as I figured it would be more likely to ring a bell to the player, but is it ok for you?
- Some biomes' names are very similar and generally translated to the same word (Flatlands and Plains --> "Plaines"), must they really be differentiated ?

**Comment by vinix38** [comment]
Also, there are some information in the launch site section that are no longer accurate. Should I update them? If yes, should I propagate these updates to the English version?

**Comment by leudaimon** [comment]
Personal opinion here, so don't see it as a "rule":

1) Feel free to improve the writing on the descriptions (both in the translation and the original). If the sentences are complicated, they can certainly be improved

2) I would say it's fine to add a few, but don't overdo it. Ditto for English. In general, whatever you are doing that improves the text, should be added also to English.

3) I think those should keep the official name in Latin. Does the English version bring English translations for these?

4) Biomes of a given body need unique names, otherwise it would be a mess to the player. Try to be creative 

5) Please, do update whatever inaccuracy you find, both in English and French.

**Comment by siimav** [comment]
Done in #244 and #245
