### ISSUE TITLE
Lack of Charon - affecting Principia

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealSolarSystem#30]
@eggrobin pointed out that the lack of Charon is greatly affecting Pluto (makes sense)

Creating this Issue as a To-Do reminder for anyone with the know-how to create a new body, even just as a filler.

Even without a heightmap (hell, or a surface even, just PQS like a gas giant would help) having a body with Charon's orbital properties and mass will help stabilize Pluto.

**Comment by grayduster** [comment]
How is the lack of Charon affecting Pluto?  As far as I was aware, the orbital characteristics (retrieved from HORIZONS) are based relative to the primary body (Sun in the case of planets and the planet they're orbiting in case of a moon), and again, I'm not sure we can do co-orbiting bodies in any case, where the centre is outside of Pluto's radius.

I did put in a filler body for Charon with the correct attributes for it based on HORIZONS - check with Nathan, as I think he removed it due to lack of available texturing.

**Comment by stratochief66** [comment]
@grayduster the Pluto data may work satisfactorily on rails (I personally can't say, I am an inner solar system pleb) but @eggrobin is modelling gravitational behaviour on not-rails, so he needs a Charon body to work with.

**Comment by grayduster** [comment]
If you look at RSSKopernicus.cfg, line 5452, you can remove the zz to renable Charon locally.  It's disabled in the public release due to lack of heightmap at the moment but is easily reenabled, but the figures should be correct for it - certainly enough for @eggrobin to use.

**Comment by stratochief66** [comment]
Charon appears to now exist in regular RSS. Closing.
